//
//  LocalizationSystem.swift
//
//
//  Created by Виктор on 24.08.2023.
//

import Foundation

public struct LocalizationSystem {
    public static var subject = "SUBJECT"
    public static var commonName = "Common Name"
    public static var country = "Country"
    public static var organization = "Organization"
    public static var state = "State"
    public static var location = "Location"
    public static var organizationalUnit = "Organizational Unit"
    public static var email = "Email Address"
    public static var issuer = "ISSUER"
    public static var validityPeriod = "VALIDITY PERIOD"
    public static var validityBefore = "Validity Before"
    public static var validityAfter = "Validity After"
    public static var validFor = "Valid For"
    public static var willExpireIn = "Will Expire In"
    public static var keyUsage = "KEY USAGE"
    public static var basic = "Basic"
    public static var extended = "Extended"
    public static var publicKey = "PUBLIC KEY"
    public static var signatureAlgorithm = "Signature Algorithm"
    public static var signature = "Signature"
    public static var keyIdentifier = "KEY IDENTIFIER"
    public static var subjectKeyId = "Subject"
    public static var authorityKeyId = "Authority"
    public static var metadata = "METADATA"
    public static var serialNumber = "Serial Number"
    public static var certificateAuthority = "Certificate Authority"
    public static var version = "Version"
    public static var daysCount = "%d days"
    public static var daysMonthsCount = "%d months %d days"
    public static var daysMonthsYearsCount = "%d years %d months %d days"
    public static var error = "ERROR"
    public static var errorDescription = "Something got wrong"
    public static var ok = "OK"
    public static var value = "Value"
    public static var critical = "Critical"
    public static var userID = "UserID"
    public static var modulus = "Modulus"
    public static var decimal = "Decimal"
    public static var blockSize = "Block size"
    public static var keySize = "Key size"
    public static var fingerPrints = "Fingerprints"
    public static var sha256 = "SHA-256"
    public static var sha1 = "SHA-1"
    public static var expired = "Expired"
    public static var digitalSignature = "Digital Signature"
    public static var nonRepudiation = "Non Repudiation"
    public static var keyEncipherment = "Key Encipherment"
    public static var dataEncipherment = "Data Encipherment"
    public static var keyAgreement = "Key Agreement"
    public static var keyCertSign = "Key CertSign"
    public static var CRLSign = "CRLSign"
    public static var encipherOnly = "Encipher Only"
    public static var decipherOnly = "Decipher Only"
    public static var serverAuth = "Server Auth"
    public static var clientAuth = "Client Auth"
    public static var codeSigning = "Code Signing"
    public static var emailProtection = "Email Protection"
    public static var timeStamping = "Time Stamping"
    public static var OCSPSigning = "OCSP Signing"
    public static var certificateTransparency = "Certificate Transparency"
    public static var any = "Any"
    public static var yes = "Yes"
    public static var no = "No"
    public static var sha1RSAEncryption = "SHA-1 With RSA Encryption"
    public static var sha256RSAEncryption = "SHA-256 With RSA Encryption"
    public static var sha384RSAEncryption = "SHA-384 With RSA Encryption"
    public static var sha512RSAEncryption = "SHA-512 With RSA Encryption"
    public static var sha1ECDSAEncryption = "SHA-1 With ECDSA Encryption"
    public static var sha384ECDSAEncryption = "SHA-384 With ECDSA Encryption"
    public static var sha512ECDSAEncryption = "SHA-512 With ECDSA Encryption"
    public static var subjectKeyIdentifier = "Subject Key Identifier"
    public static var subjectAlternativeName = "Subject Alternative Name"
    public static var basicConstraints = "Basic Constraints"
    public static var cRLDistributionPoints = "cRLDistributionPoints"
    public static var certificatePolicies = "Certificate Policies"
    public static var authorityKeyIdentifier = "Authority Key Identifier"
    public static var externalKeyUsage = "External KeyUsage"
    public static var authorityAccess = "Authority Access"
    public static var OID = "OID"
}
